# Docs: https://goreleaser.com/

project_name: airplane
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/airplane/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: windows
        goarch: 386
    mod_timestamp: "{{ .CommitTimestamp }}"
archives:
  - files: [only-the-binary*]
    wrap_in_directory: false
    # This is the default name_template, but without the version. This allows install.sh to compute the
    # latest artifact name without knowing the version.
    name_template: |
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}
    replacements:
      amd64: x86_64
  - id: binary
    format: binary
    files: [only-the-binary*]
    # This is the default name_template, but without the version. This allows install.sh to compute the
    # latest artifact name without knowing the version.
    name_template: |
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}
    replacements:
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
brews:
  - tap:
      owner: airplanedev
      name: homebrew-tap
    homepage: "https://airplane.dev"
    test: |
      system "#{bin}/airplane help"
    commit_author:
      name: AirplaneBot
      email: bot-github@airplane.dev
    install: |
      bin.install "airplane"
release:
  prerelease: auto
  extra_files:
    # Upload our installation scripts as release artifacts:
    - glob: ./scripts/install*
