name: release

on:
  push:
    tags:
      - "v*"

env:
  GOOGLE_CREDENTIALS_FILE_PATH: .google_credentials

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: airplane-prod
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true
          credentials_file_path: ${{ env.GOOGLE_CREDENTIALS_FILE_PATH }}
      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker us-docker.pkg.dev
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          SEGMENT_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
